FROM debian:wheezy

ENV DEBIAN_FRONTEND=noninteractive

RUN echo "deb http://archive.debian.org/debian wheezy main contrib non-free" > /etc/apt/sources.list && \
    echo "deb http://archive.debian.org/debian-security wheezy/updates main contrib non-free" >> /etc/apt/sources.list && \
    echo "Acquire::Check-Valid-Until false;" > /etc/apt/apt.conf.d/99no-check-valid && \
    echo "Acquire::AllowInsecureRepositories true;" > /etc/apt/apt.conf.d/99insecure && \
    echo "APT::Get::AllowUnauthenticated true;" >> /etc/apt/apt.conf.d/99insecure && \
    apt-get -o Acquire::Check-Valid-Until=false update

RUN apt-get install -y --force-yes \
    build-essential gcc make valgrind

WORKDIR /app

COPY *.c *.h Makefile /app/

RUN make

CMD ["/app/ft_ping"]

